### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by codermert** [alexllanas/open-audio#1]
Uploading music from app not working

**Comment by alexllanas** [comment]
I'm actually working on that right now. I still have to redesign the UI for the upload portion of the app. Once that's finished, you should be able to search for a track given a YouTube url and either upload a new instance of that track to the server or add an existing track to a playlist if it has already been uploaded by someone else. The user shouldn't know the difference because when a URL is entered, it should just display a list of tracks, with the new track listed first. This is just mimicking the same functionality from openwhyd.org.

**Comment by alexllanas** [comment]
I've added this feature, but a few bugs remain:

- After uploading a track, navigating from and back to new track screen causes track to re-upload. 
- Cover image for track is not being set properly when using metadata to create a new Track object.
- Track options and Like actions are not working.
